debug=false

logging.level.org.springframework.web.servlet.DispatcherServlet=debug
logging.level.hu.bendeguz.kodokharca=trace
logging.pattern.console=%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss}}){faint} %clr(${LOG_LEVEL_PATTERN:- [%5p]}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}

server.servlet.context-path=/kodokharca
server.port=8082

#thymeleaf
spring.thymeleaf.cache=false
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.enable-spring-el-compiler=true
